### ISSUE TITLE
Mandrill Free Tier Lowered from 12k to 2k per month!!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sendemail#14]
Mandril *used* to give **12k** "***Free***" sends per month....

![mandril-pricing-2k-free](https://cloud.githubusercontent.com/assets/194400/10597976/42d37fac-76ec-11e5-8888-fc87dada0f74.png)

*Obviously* people were *abusing* the free tier... but this is quite a *drastic* reduction...

if *anyone* else agrees that we need to support other senders, please ***Tell Us*** which provider you want us to support.

**Comment by drinkbird** [comment]
SendGrid offers free and light plans, it looks like a good alternative.

**Comment by nelsonic** [comment]
@drinkbird do you have time to help us write the code & docs/instructions for using sendgrid?

**Comment by drinkbird** [comment]
@nelsonic I would be happy to help, although I just came across sendgrid today and I haven't actually used it yet. I expect the code to be minimal, since they already have a node package for it: https://sendgrid.com/docs/Integrate/Code_Examples/nodejs.html

IMO the real challenge is to refactor sendemail to support providers as plugins, and then it would just need a simple adapter for each.

I'm going to update this issue later within the month, as I'm going to evaluate sendgrid by using it in a small project.

**Comment by nelsonic** [comment]
Sounds like a good plan. Keep us informed of your progress. Thanks. :wink:

**Comment by iteles** [comment]
Mandrill free tier is disappearing completely! http://blog.mailchimp.com/important-changes-to-mandrill/
:disappointed: 

@drinkbird Did you have any joy with sendgrid? :relaxed:

**Comment by nelsonic** [comment]
We're going to use Gmail... but it will take a couple of days worth of programming...

**Comment by drinkbird** [comment]
The project's stakeholders decided to use sendgrid's nodejs library directly so I haven't tried to write an adapter for sendemail.

About Gmail, I've tried to use its API but I haven't been successful so far. I need to figure out how to authorize the web application, get a token back and use it to send emails. https://developers.google.com/gmail/api/

**Comment by nelsonic** [comment]
Closing.
